### ISSUE TITLE
How to update an existing jpeg texture (embedded)

### ISSUE THREAD

**Issue by davelajoie** [sergkr/gltflib#139]
Question....
Hello!

I have glb files, which contains only 1 embedded texture ( binary,  not base64 ), and I would like to remove the embedded texture and replace it with a new binary embedded texture.
what is the proper way to "update in-place" an existing texture with a new texture ( different size ).
Tx a lot
Dave.

**Comment by davelajoie** [comment]
Found a solution... but for the sake of doing it "correctly", just wanted to know if there was a cleaner way to do it. tx

`    with open( str( inTextureFilePathStr ) , 'rb' ) as fh:
        texByteArray = bytearray( fh.read() )
        texlen       = len( texByteArray )
        # texture is at the end of the buffer
        textureOffset = gltf.model.bufferViews[ -1 ].byteOffset
        meshData      = gltf.resources[0].data[0:textureOffset]
        newData       = meshData + texByteArray

        # update new buffer
        gltf.resources[0].data = newData
        gltf.model.bufferViews[-1].byteLength = texlen
        gltf.model.buffers[0].byteLength      = len( newData )
`

**Comment by sergkr** [comment]
Hi @davelajoie!

There's not really a built in way to do this via the library when dealing with a GLB, but your approach is basically correct (as long as you can guarantee the texture is always going to be in the last buffer view).

If there are more buffer views, it gets a bit trickier since now you have to update the offsets on all subsequent buffer views. You would also want to ensure the texture data is padded with NULLs, so that subsequent buffer views align to a 4-byte boundary.

I don't have this as a feature yet, but something that could potentially make this scenario easier is to have the ability to "un-embed" buffer views and save them as external resources. Then you would be able to swap out those resources, and then re-embed them and save as a GLB again. I'll implement this if I see more requests for it - but in the meantime, what you have is the best approach available.
