### ISSUE TITLE
Easy way to extract glb vertices

### ISSUE THREAD

**Issue by MikelAyani** [sergkr/gltflib#14]
This is just a question because I did not find an example of that. Is there any way to extract just the vertices of each mesh included in a glb file using this library?

**Comment by sergkr** [comment]
Not really an easy way, no. This library just provides a set of classes that implement the [spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0) so you can construct or dissect a model with the benefits of strong typing/intellisense. Extracting or working with the geometry data is a bit outside the scope.

Depending on what you're trying to do, you might want to take a look at [trimesh](https://github.com/mikedh/trimesh) - which is more oriented at working with geometry (and also supports loading glTF). Here's a quick example that iterates over each mesh in the [Buggy](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy) sample model and dumps the mesh name and vertices:

```
import trimesh

mesh = trimesh.load('glTF-Sample-Models/2.0/Buggy/glTF/Buggy.gltf')
for name, geom in mesh.geometry.items():
    print(name)
    print(geom.vertices)
```

Otherwise, if you're using this library, you just have to go through the whole hierarchy yourself - for each mesh, find the corresponding primitives, then the corresponding accessors, buffer views, and finally buffers, and then use [struct.unpack_from](https://docs.python.org/3/library/struct.html#struct.unpack_from), making sure to take the offset, stride, etc. into account.
