### ISSUE TITLE
Unexpected EOF when parsing binary chunk body. The GLB file may be corrupt.

### ISSUE THREAD

**Issue by MikelAyani** [sergkr/gltflib#37]
I have noticed that some Glb files get 'corrupted' somehow when opened and edited with 3D Builder in Windows. For example, the one shown in the picture below can be opened in the online GLTF viewer and shown, but it gives some errors:
![image](https://user-images.githubusercontent.com/36505430/80967445-aeb8e900-8e16-11ea-9dbd-b2f13f1a336c.png)
![image](https://user-images.githubusercontent.com/36505430/80967471-b8425100-8e16-11ea-8fc6-cd32cd35b3c3.png)
The library raises a RuntimeError if I try to open the same file, but if I disable the check inside _load_glb_binary_chunk_body() method the library can parse the file. Is there any chance I could decide to disable some checks using a flag or something similar?

**Comment by sergkr** [comment]
Yep, after thinking about it some more, I don't see any reason to artificially limit the utility of this library by throwing an error when loading a model that isn't fully up to spec. As long as it can still parse the header and JSON body, that's all it really needs. Anything else should be a runtime warning, and then it's up to the consumer of the library to deal with if needed.

I went ahead and made the change to emit a warning instead of raising an error in this scenario, and released an updated version of this library just now (v1.0.5). Thanks for reporting, and let me know if you see any other issues.
